version: "3.5"

services:
  app:
    container_name: ${APP_CONTAINER}
    image: ${IMAGE}
    restart: always
    ports:
      - ${PORT}:80
    networks:
      - production
    external_links:
      - ${API_CONTAINER}

networks:
  production:
    external: true